### ISSUE TITLE
Fix Bug: Transition Between Town and Forest & Entering/Exiting Houses

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#143] opened 2024-11-21 00:10 UTC
### Scope
We have detected a bug with the Area Exit functionality in the Town scene, specifically in the following cases:

Area Exit: Town to Forest:
This Area Exit is not working

https://github.com/user-attachments/assets/2d211208-f919-4375-91b5-88d718ab6026

Area Exit: Exiting Houses to Town:
While the Area Exit works and allows the player to exit the house and return to the Town, the main character respawns at a different location in the Town instead of near the door of the house they entered.

https://github.com/user-attachments/assets/91d38d19-7ec5-4526-8c23-9a165b7ee71f

Your task is to investigate the bug, understand the issue, and implement a fix.

### How Area Exit are implemented?
- In the Town scene, you will find all the Area Exits currently present in the scene.
![image](https://github.com/user-attachments/assets/e80d7818-fc0c-4684-91f2-c5d6ee700aa8)

- Each Area Exit is a prefab with its own specific configurations, which you can inspect in the Inspector window on the right side of the screen.
![image](https://github.com/user-attachments/assets/69c13cc0-4a73-4a0f-818b-9c0c808a14eb)

How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by MrRoudyk** [comment] 2024-11-21 06:37
May I take care of this?

**Comment by mimisavage** [comment] 2024-11-21 07:03
Would love to tackle this!

**Comment by josephchimebuka** [comment] 2024-11-21 07:06
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. I'd love to give this a go. I should complete project in 3-4 days

**Comment by baitcode** [comment] 2024-11-21 09:25
I have experience making 2D games in Unity and interested to solve this. 
Not sure if I can provide exact plan on how I will approach this as this is a research task.

**Comment by JP-the-Analyst** [comment] 2024-11-21 09:26
Hello I'm ready to contribute to this project as soon as you give me the green light. Although I'm new to Unity and the project, I'm eager to learn and contribute to the community. To resolve this issue, I plan to start by carefully reading through the provided documentation and existing code to understand how the Area Exit functionality is currently implemented.
 I'll then investigate the specific cases where the bug occurs, such as the transition from Town to Forest and exiting houses to Town. Utilising my problem solving skills, i'll identify the root cause of the issue and implement a fix, which may involve modifying existing scripts or creating new ones. I'm confident that with guidance from the project maintainers and the community, I can successfully resolve this bug and improve the overall gaming experience for users. I'm looking forward to the opportunity to learn and grow with the ByteBeasts team.

Ready when you are, captain!

**Comment by Akshola00** [comment] 2024-11-21 14:31
Let me try this one!

**Comment by Unickhub** [comment] 2024-11-21 14:44
Can I be assigned to this?

**Comment by FemiOje** [comment] 2024-11-21 15:10
gm. I'm jinius and I have 1+ year experience with Unity  and C#. I'm looking to contribute to ByteBeasts for the first time hopefully.

How I would approach this issue:
1. setup project locally, following the contribution guidelines.( I have Unity version 2022.3.28.f1 installed.)
2. Open the Town scene and set the Area to Load property on the appropriate AreaExit prefab to Forest.
3. For each house, set the theEntrance AreaEntrance values to correspond to the appropriate transform in the town(in front of each house).
4. Test to make sure the issue is resolved and there are no bugs.
5. Commit and push changes to my branch, and submit pull request.

If the issue persists, I will inspect the Area Exit script to ensure that it triggers as it should, and communicate with the project maintainers accordingly.

Estimated time it would take to resolve: 1 - 2 days

**Comment by ShantelPeters** [comment] 2024-11-21 15:10
Let me try this one!

**Comment by Michaelkingsdev** [comment] 2024-11-21 15:18
Could I be assigned to this?

**Comment by Supa-mega** [comment] 2024-11-21 18:55
Is it okay if I tackle this?

**Comment by 0xDeon** [comment] 2024-11-22 00:08
Could I take a shot at this?
I am a new contributor to this project and would love the opportunity of contributing to Bytebeats

How I plan to handle this issue
- I'll start by investigating the bug; checking how exiting the forest works, then try to make sure the functionality in the town is of the same sort
- Then I'll look at the spawn position to make sure it is accurate

**Comment by aniruddhaaps** [comment] 2024-11-22 08:17
The common problem of smooth transition between town, forest, and house areas could be solved with:

Firstly refactor the scripts AreaExit and AreaEntrance so that the proper loading and unloading of scenes occur while dynamically updating the property AreaToLoad in line with the choices made by the player. Test all transitions while ensuring there isn't any confusion between Unity's triggers and colliders, which can lead to a misaligned region.

**Comment by jimenezz22** [comment] 2024-11-22 13:11
@FemiOje assigned to you

**Closed as completed** 2024-11-26 19:29 UTC
Labels: bug, good first issue, external-contributor
