### ISSUE TITLE
Add Menu Button

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#98] opened 2024-10-23 20:07 UTC
### Scope
- We need to add a new buttom in the game scenes that allows the acces to the gamplay panels, take a look in the issue #97 to undestand more about what is this panels. 
 - The buttom should be implemented in the path: Assets/Prefabs/UI Canvas.prefab in the component: Meu/Buttoms
 - The asset for the buttom will be provided to the contributor once the issue is assigned.
 - Please put this assets in the path Assets/Battle Assets/Art/UI
 ### This is how panel hierarchy looks in Unity
<img width="263" alt="Screenshot 2024-10-23 at 2 03 37 PM" src="https://github.com/user-attachments/assets/c7c3300b-21e6-40dd-ad0d-7cb5f419a21f">

**Comment by martinvibes** [comment] 2024-10-24 07:02
hello @jimenezz22  i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by josephchimebuka** [comment] 2024-10-24 07:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will follow the description to be able to add the menu button

**Comment by KevinLatino** [comment] 2024-10-24 07:05
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.



### How I plan on tackling this issue
I would begin by thoroughly reviewing issue #97 to understand the functionality and purpose of the gameplay panels. After that, I’ll examine the `UI Canvas.prefab` located at `Assets/Prefabs/UI Canvas.prefab`, focusing on the `Menu/Buttons` component to ensure the new button fits seamlessly with the existing UI structure. Once I receive the button asset, I’ll import and integrate it into the prefab, maintaining consistency with the current UI elements. My approach will ensure the button functions as intended and enhances the overall user experience by providing quick access to the gameplay panels.

**Comment by suhas-sensei** [comment] 2024-10-24 07:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev previously as personal projects and hoping to make use of them here.

### How I plan on tackling this issue
here is going to be my approach
1. Create a button GameObject inthe UI Canvas/Menu/Buttons
2. Naming as "GameplayPanels_Button" (or similar)
3. Within the Assets/Prefabs/UI Canvas.prefab, Menu/Buttons componentt
4. Attach the required button components: Image, Button component
5. Wait for the assignee to provide the button asset
6. Attach the onClick event to access gameplay panels

Location will be as per that ss : Assets/Prefabs/UI Canvas.prefab
Component Path: Menu/Buttons

**Comment by DiegoB1911** [comment] 2024-10-24 07:20
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.

### How I plan on tackling this issue
To solve this, I will:
1. Understand the Gameplay Panels.
2. Add the new button.
3. Link the button to the Gameplay Panels.
4. Test the button.

**Comment by jsandinoDev** [comment] 2024-10-24 08:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm a full-stack developer with web3 experience member of Dojo Coding, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

### How I plan on tackling this issue
1. Understand the Context
From the description, the button will provide access to gameplay panels, and more information can be found in issue #97. Ensure you read through that issue to understand the purpose of the panels and how users should interact with them.
2. Button Location
The new button should be added in the following location:

Path: Assets/Prefabs/UI Canvas.prefab
Component: Menu/Buttons
This is where the button will be placed in the UI Canvas of the game scenes.
3. Steps to Implement the Button
a. Navigate to the UI Canvas Prefab
In Unity, go to the Project panel.
Locate the path: Assets/Prefabs/UI Canvas.prefab.
Double-click the UI Canvas prefab to open it.
b. Locate the Menu/Buttons Component
Inside the UI Canvas, look for the Menu GameObject.
Inside the Menu, find the Buttons component (or GameObject), where the existing buttons are located.
c. Create the New Button
Right-click on the Buttons component in the Hierarchy and select UI > Button to add a new button.
Name the button appropriately (e.g., GameplayPanelsButton).
d. Set Up Button Properties
Set the Button Text: Edit the text of the button to reflect its purpose (e.g., "Gameplay Panels").
Apply the Provided Asset: Once you receive the button asset, apply it by setting it as the button’s image.
Select the button.
In the Inspector, find the Image component and replace the default image with the provided button asset.
e. Add the Button Logic
Attach a script to the button that handles the interaction. The script should control access to the gameplay panels described in issue #97.

**Comment by Benjtalkshow** [comment] 2024-10-24 09:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To tackle this, I’ll first review issue #97 to understand the gameplay panels. Then, I’ll navigate to Assets/Prefabs/UI Canvas.prefab and locate the Meu/Buttons component. After that, I’ll add the new button using the provided asset, ensuring it integrates well with the existing UI. Finally, I’ll test the functionality to confirm it accesses the gameplay panels correctly.

**Comment by mexes20** [comment] 2024-10-24 09:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 6 years experience

ETA: One day

**Comment by blessingbytes** [comment] 2024-10-24 10:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello i'm a frontend and blockchain developer, pls i would love to take this task

### How I plan on tackling this issue
To effectively resolve this issue, i would start by adding a new button in the game scenes that allows access to the gameplay panels.

**Comment by Ayoazeez26** [comment] 2024-10-24 11:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Add the button in the game scenes that would allow access to the gameplay
ETA - 2 days

**Comment by ShantelPeters** [comment] 2024-10-24 12:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have a solid understanding of Unity and UI design, with experience in creating and managing UI components within game scenes. My familiarity with prefab structures and Unity's hierarchy will enable me to effectively implement new buttons and connect them to the gameplay functionality as required.

### How I plan on tackling this issue
 I will begin by reviewing issue #97 to fully understand the functionality and requirements of the gameplay panels. Then, I will access the prefab located at Assets/Prefabs/UI Canvas. prefab and navigate to the Menu/Buttons component. After that, I will add the new button, ensuring it matches the design and functionality of existing buttons. I will then implement the necessary scripts to link the button to the gameplay panels. Finally, I will test the integration in the game to ensure seamless functionality before submission

**Comment by 0xBinayak** [comment] 2024-10-24 12:46
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
 I am new to OS but  I have been doing game dev for a year,made 2 personal games and worked on multiple  projects in unity with C#.

### How I plan on tackling this issue
I would add main menu  button that will aloow access to the gameplay panels  and the menu button will be implemented in Assets/Prefabs/UI Canvas.prefab .
 ETA :1 day

**Comment by BrunoAmbricca** [comment] 2024-10-24 12:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hey guys, Bruno here from the dojo coding community. I´ve been working for the past 4 years with c# and in big companies like the one Im right one (Mercado Libre) so I have encountered a lot of documentation.

### How I plan on tackling this issue
I would look how other buttons are coded in the project, to follow the same pattern and code the proper behavior

**Comment by caxtonacollins** [comment] 2024-10-24 15:20
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am applying to this issue via https://app.onlydust.com/hackathons/odhack-90.

I am Collins Cxaton, a fullstark developer with a strong background in integrating APIs and designing responsive UI components based on Figma designs. I have experience in working with cryptocurrency wallets and displaying real-time wallet balances by integrating financial APIs. My skills in React and JavaScript allow me to effectively manage currency conversions and data handling.

### How I plan on tackling this issue
i will love to contribute to this project

**Comment by aniruddhaaps** [comment] 2024-10-24 15:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm a javascript dev. A new-comer here, willing and ready to contribute to solve the issue.

**Comment by jimenezz22** [comment] 2024-10-24 21:59
gm @jsandinoDev assigned to you.
here the panel and home buttom assets to work:
[ByteBeasts_HomeButton_Assets.zip](https://github.com/user-attachments/files/17513341/ByteBeasts_HomeButton_Assets.zip)

**Comment by Jemiiah** [comment] 2024-10-25 12:40
hello @jimenezz22 would they be more issues released later on

**Closed as completed** 2024-11-01 17:23 UTC
Labels: enhancement, good first issue, external-contributor
